INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(1,'Pizza tradicional familiar',2,100,200);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(1,'Coca-Cola 600ml.',1,18,18);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(3,'Pizza de la casa personal',1,90,90);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(3,'Espagueti',1,65,65);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(4,'Coca-Cola 600ml.',1,18,18);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(5,'Te olong',2,15,30);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(5,'Arma tu pizza familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(6,'Coca-Cola lata',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(7,'Pizza tradicional familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(7,'Coca-Cola 600ml.',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(7,'Jamaica',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(8,'Pizza tradicional personal',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(9,'Coca-Cola 600ml.',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(10,'Pizza tradicional personal',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(10,'Te olong',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(11,'Coca-Cola lata',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(12,'Pizza de la casa familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(12,'Coca-Cola 600ml.',2,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(12,'Te olong',2,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(13,'Arma tu pizza familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(14,'Pizza tradicional personal',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(15,'Pizza tradicional familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(16,'Pizza de la casa personal',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(17,'Pizza tradicional familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(17,'Agua Ciel',2,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(17,'Te olong',2,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(17,'Coca-Cola 600ml.',2,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(18,'Arma tu pizza familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(18,'Te olong',2,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(18,'Coca-Cola 600ml.',2,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(18,'Espagueti',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(19,'Pizza tradicional familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(19,'Te olong',2,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(19,'Coca-Cola 600ml.',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(20,'Pizza tradicional familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(21,'Arma tu pizza familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(21,'Pizza de la casa personal',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(21,'Arma tu pizza personal',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(21,'Te olong',4,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(21,'Espagueti',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(21,'Coca-Cola 600ml.',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(21,'Pizza de la casa familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(22,'Agua Ciel',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(23,'Pizza tradicional personal',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(23,'Te olong',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(23,'Coca-Cola 600ml.',2,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(23,'Agua Ciel',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(23,'Pizza de la casa personal',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(24,'Pizza de la casa personal',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(25,'Pizza de la casa familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(26,'Arma tu pizza personal',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(27,'Arma tu pizza familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(27,'Coca-Cola 600ml.',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(27,'Te olong',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(28,'Pizza de la casa familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(28,'Te olong',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(29,'Te olong',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(30,'Coca-Cola 600ml.',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(31,'Pizza de la casa familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(31,'Te olong',4,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(32,'Te olong',2,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(32,'Pizza de la casa familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(33,'Agua Ciel',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(34,'Pizza tradicional familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(35,'Pizza tradicional familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(36,'Pizza tradicional familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(37,'Pizza tradicional familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(38,'Pizza tradicional familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(39,'Pizza tradicional familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(40,'Pizza tradicional familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(41,'Pizza tradicional familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(42,'Pizza tradicional familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(43,'Arma tu pizza familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(43,'Te olong',2,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(44,'Pizza tradicional familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(44,'Ingrediente Extra',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(44,'Coca-Cola 600ml.',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(45,'Arma tu pizza personal',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(45,'Coca-Cola 600ml.',3,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(45,'Pizza tradicional familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(46,'Te olong',4,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(46,'Pizza tradicional familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(47,'Ingrediente Extra',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(48,'Arma tu pizza personal',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(48,'Coca-Cola 600ml.',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(48,'Espagueti',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(49,'Pizza tradicional familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(50,'Te olong',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(51,'Pizza tradicional familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(52,'Arma tu pizza familiar',2,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(52,'Te olong',2,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(52,'Coca-Cola 600ml.',4,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(53,'Pizza de la casa familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(53,'Espagueti',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(53,'Te olong',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(53,'Coca-Cola 600ml.',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(54,'Coca-Cola 600ml.',2,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(54,'Pizza tradicional familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(54,'Te olong',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(54,'Ensalada Cesar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(55,'Pizza tradicional familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(56,'Pizza tradicional familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(57,'Pizza tradicional familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(58,'Agua Ciel',2,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(58,'Coca-Cola 600ml.',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(59,'Pizza tradicional familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(60,'Arma tu pizza familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(60,'Pizza de la casa personal',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(60,'Te olong',4,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(61,'Pizza tradicional familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(62,'Agua Ciel',2,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(62,'Arma tu pizza familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(63,'Pizza de la casa personal',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(64,'Pizza tradicional familiar',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(64,'Te olong',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(64,'Espagueti',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(65,'Te olong',1,0,0);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(66,'Te Olong',2,15,30);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(67,'Mexicana 35 cm normal ',1,160,160);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(68,'Arma tu pizza 25 cm normal ',1,100,100);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(68,'Suprema 35 cm normal ',1,160,160);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(68,'Naranja 600ml',1,18,18);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(68,'Agua Ciel 600ml',1,10,10);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(68,'Te Olong',2,15,30);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(69,'Arma tu pizza 35 cm normal ',1,170,170);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(70,'Clasica 35 cm normal ',1,100,100);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(70,'Clasica 25 cm normal ',1,70,70);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(70,'Coca 600ml.',1,18,18);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(71,'Lata',1,15,15);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(72,'Mexicana 35 cm normal ',1,160,160);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(72,'Fresa 600ml',2,18,36);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(72,'Ligth 600ml.',1,18,18);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(73,'Sprite 600ml',1,18,18);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(73,'Agua Ciel 600ml',1,10,10);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(73,'Lata',1,15,15);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(74,'Te Olong',1,15,15);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(75,'Arma tu pizza 25 cm normal ',1,100,100);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(75,'Coca 600ml.',1,18,18);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(76,'Arma tu pizza 35 cm normal ',1,170,170);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(76,'Coca 600ml.',2,18,36);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(76,'Manzanita 600ml',1,18,18);
INSERT INTO ventadetalle (No_ticket,Descripcion,Cantidad,Precio,Total) VALUES(77,'Coca 600ml.',1,18,18);