//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_Venta
{
    using System;
    using System.Collections.Generic;
    
    public partial class compras
    {
        public int id { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<double> Importe { get; set; }
        public int Proveedores_id { get; set; }
        public int Usuarios_id { get; set; }
        public int Productos_id { get; set; }
    
        public virtual productos productos { get; set; }
        public virtual proveedores proveedores { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
