//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_Venta
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleados
    {
        public empleados()
        {
            this.usuarios = new HashSet<usuarios>();
        }
    
        public int id { get; set; }
        public string Nombre { get; set; }
        public string Ap_paterno { get; set; }
        public string Ap_materno { get; set; }
        public Nullable<double> Sueldo { get; set; }
        public string Turno { get; set; }
        public string Puesto { get; set; }
    
        public virtual ICollection<usuarios> usuarios { get; set; }
    }
}
