//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_Venta
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        public productos()
        {
            this.compras = new HashSet<compras>();
            this.ventas = new HashSet<ventas>();
        }
    
        public int id { get; set; }
        public string Codigo_barras { get; set; }
        public string Descripcion { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public Nullable<double> Precio_compra { get; set; }
        public Nullable<double> Precio_venta { get; set; }
        public int Proveedores_id { get; set; }
    
        public virtual ICollection<compras> compras { get; set; }
        public virtual proveedores proveedores { get; set; }
        public virtual ICollection<ventas> ventas { get; set; }
    }
}
